### ISSUE TITLE
gulp dist error with $.useref.assets

### ISSUE THREAD

**Issue by TuulaP** [jiemakel/arpa-ui#2]
Hi again, next item is with gulp dist task, the $.useref.assets of  gulp-useref  with version 3.1.0  seems to be deprecated

<pre>
[14:12:07] Finished 'dist:partials' after 337 ms
[14:12:07] Starting 'dist:html'...
[14:12:07] 'dist:html' errored after 111 ms
[14:12:07] TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (/work/arpas/arpa-ui/gulp/dist.ls:19:21)
    at module.exports (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:27                    3:3)
    at Gulp.Orchestrator._runStep (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:21                    4:10)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modu                    les/once/once.js:17:25)
    at DestroyableTransform.onend (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/node_module                    s/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable                    -stream/lib/_stream_readable.js:965:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[14:12:07] 'dist' errored after 2.35 s
[14:12:07] TypeError in plugin 'run-sequence(dist:html)'
Message:
    $.useref.assets is not a function
Stack:
TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (/work/arpas/arpa-ui/gulp/dist.ls:19:21)
    at module.exports (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:27                    3:3)
    at Gulp.Orchestrator._runStep (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:21                    4:10)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modu                    les/once/once.js:17:25)
    at DestroyableTransform.onend (/work/arpas/arpa-ui/node_modules/gulp/node_modules/orchestrator/node_module                    s/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at /work/arpas/arpa-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable                    -stream/lib/_stream_readable.js:965:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[14:12:07] Finished 'dist:fonts' after 207 ms
</pre>

Thanks again, one alternative could be downgrade to older module version, but not sure if there is then another impact elsewhere.

**Comment by jiemakel** [comment]
I pushed new bower.json and package.json definitions that explicitly refer to known working versions of the build chain (this is actually an ugly fix, and I've resolved this better in other projects, but can't be bothered to do that here just now)
